export const SecurityOptions = {
  JWT_EXPIRATION_TIME: '7d',
  PASSWORD_SALT_ROUNDS: 10,
  FILE_SIGN_TIME: 60, // 1 minute
  ATTEMPT_FAILURE_LIMIT: 5,
  LOGIN_LOCKOUT_LIMIT: 20,
  LOCKOUT_DURATION: 5 * 60, // 5 minutes
  OTP_EXPIRATION_TIME: 5 * 60, // 5 minutes
  DEFAULT_PASSWORD: 'HACKATHON@2025',
  PDF_PREVIEW_PAGE_LIMIT: 3,
};
